In [1]:
lst=[1,2,3]

In [2]:
import numpy as np

In [3]:
arr=np.array(lst)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_list=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
 np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.30663344, 0.99300351, 0.45708005, 0.28214859, 0.97123329])

In [23]:
np.random.rand(5,5)

array([[0.66992802, 0.21357311, 0.26799099, 0.2808988 , 0.74948732],
       [0.42637414, 0.79334983, 0.4269442 , 0.24788387, 0.52883883],
       [0.75954475, 0.35287101, 0.83152554, 0.80966316, 0.64837947],
       [0.78810315, 0.32903964, 0.66523283, 0.96079788, 0.75119067],
       [0.52866241, 0.85532997, 0.46713363, 0.50985521, 0.9299912 ]])

In [26]:
np.random.randn(2,2)#normal distribution

array([[-0.79827646, -0.45051549],
       [-0.93745948,  0.82824854]])

In [31]:
np.random.randint(1,100)

93

In [32]:
 np.random.randint(1,100,10)

array([88, 73, 76, 99, 60, 63, 76, 18, 43, 96])

In [33]:
arr=np.arange(25)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
ranarr=np.random.randint(0,50,10)

In [36]:
ranarr

array([ 6, 14, 40, 27,  2, 35, 13, 32, 30, 43])

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr

array([ 6, 14, 40, 27,  2, 35, 13, 32, 30, 43])

In [39]:
ranarr.max()

43

In [40]:
ranarr.min()

2

In [41]:
ranarr.argmin()

4

In [42]:
ranarr.argmax()

9

In [43]:
arr.shape


(25,)

In [44]:
arr=arr.reshape(5,5)

In [45]:
arr.shape

(5, 5)

In [46]:
arr.dtype

dtype('int32')

In [47]:
from numpy.random import randint

In [48]:
randint(2,10,2)

array([5, 7])