In [29]:
import numpy as np

In [30]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [31]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
arr_2d[0][0]

5

In [33]:
arr_2d[0]

array([ 5, 10, 15])

In [34]:
arr_2d[2][1]

40

In [35]:
arr_2d[2,1]

40

In [36]:
arr_2d[1,2]

30

In [40]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [42]:
arr_2d[:,1]

array([10, 25, 40])

In [3]:
import numpy as np

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5]=100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr=np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_arr=arr[0:6]

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [17]:
 #!IMPORTANT!!!!!

In [18]:
slice_of_arr[:]=99

In [19]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy=arr.copy()

In [22]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy[:]=100

In [24]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [49]:
 #CONDITIONAL SELECTION

In [50]:
arr=np.arange(1,11)

In [51]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [53]:
bool_arr=arr>5

In [54]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [55]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [56]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [58]:
arr[arr<=3]

array([1, 2, 3])

In [59]:
arr.dtype

dtype('int32')

In [61]:
np.random.rand()

0.8926240786377995

In [ ]:
[1:3,3:5]